#!/usr/bin/env bash
# Creates an Azure VM prepared for the AmneziaVPN desktop client.
# This script does NOT install any VPN software -- Amnezia's client does
# that over SSH, because it has no headless mode.
set -euo pipefail

REPO_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
# shellcheck source=../lib/common.sh
source "$REPO_ROOT/lib/common.sh"

require_cmd az
require_cmd curl
require_az_login
load_config "$REPO_ROOT/config.env"

: "${VM_SIZE:=Standard_B1s}"
: "${OS_DISK_SIZE_GB:=32}"
: "${OS_DISK_SKU:=StandardSSD_LRS}"
: "${IMAGE_URN:=Canonical:ubuntu-24_04-lts:server:latest}"
: "${XRAY_PORT:=443}"

IP_NAME="${VM_NAME}-ip"
NSG_NAME="${VM_NAME}-nsg"

if [[ -z "${SSH_ALLOWED_IP:-}" ]]; then
  SSH_ALLOWED_IP="$(detect_public_ip)"
  log_info "detected your public IP as $SSH_ALLOWED_IP"
else
  validate_ipv4 "$SSH_ALLOWED_IP" || die "SSH_ALLOWED_IP '$SSH_ALLOWED_IP' is not a valid IPv4 address"
fi

if az vm show -g "$RESOURCE_GROUP" -n "$VM_NAME" >/dev/null 2>&1; then
  log_warn "VM '$VM_NAME' already exists in '$RESOURCE_GROUP' -- nothing to create."
  log_warn "Run scripts/destroy.sh first if you want a clean rebuild."
  exit 0
fi

log_info "creating resource group '$RESOURCE_GROUP' in '$LOCATION'"
az group create -n "$RESOURCE_GROUP" -l "$LOCATION" --output none

ADMIN_PASSWORD="$(generate_password)"

log_info "creating VM '$VM_NAME' ($VM_SIZE, $OS_DISK_SIZE_GB GB $OS_DISK_SKU)"
az vm create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$VM_NAME" \
  --location "$LOCATION" \
  --image "$IMAGE_URN" \
  --size "$VM_SIZE" \
  --admin-username "$ADMIN_USER" \
  --admin-password "$ADMIN_PASSWORD" \
  --authentication-type password \
  --os-disk-size-gb "$OS_DISK_SIZE_GB" \
  --storage-sku "$OS_DISK_SKU" \
  --public-ip-address "$IP_NAME" \
  --public-ip-sku Standard \
  --public-ip-address-allocation static \
  --nsg "$NSG_NAME" \
  --nsg-rule NONE \
  --custom-data "$REPO_ROOT/cloud-init/swap.yaml" \
  --output none

PUBLIC_IP="$(az network public-ip show -g "$RESOURCE_GROUP" -n "$IP_NAME" --query ipAddress -o tsv)"
IMAGE_EXACT="$(az vm show -g "$RESOURCE_GROUP" -n "$VM_NAME" \
  --query storageProfile.imageReference.exactVersion -o tsv)"

log_info "VM created. Public IP: $PUBLIC_IP  (image $IMAGE_EXACT)"

add_nsg_rule() {
  local name="$1" priority="$2" protocol="$3" port="$4" source="$5"
  log_info "NSG rule: $name ($protocol/$port from $source)"
  az network nsg rule create \
    --resource-group "$RESOURCE_GROUP" \
    --nsg-name "$NSG_NAME" \
    --name "$name" \
    --priority "$priority" \
    --direction Inbound \
    --access Allow \
    --protocol "$protocol" \
    --source-address-prefixes "$source" \
    --destination-port-ranges "$port" \
    --output none
}

# SSH is reachable only from the operator. Password authentication stays
# enabled because Amnezia's installer needs it and re-enabling it for every
# protocol change is friction; this source restriction is what actually
# protects the port. The retired deployment had password auth enabled AND
# port 22 open to the entire internet.
add_nsg_rule ssh       300 Tcp 22                  "$SSH_ALLOWED_IP"
add_nsg_rule xray      310 Tcp "$XRAY_PORT"        '*'
add_nsg_rule amneziawg 320 Udp "$AMNEZIAWG_PORT"   '*'

umask 077
cat > "$REPO_ROOT/.env" <<ENVFILE
# Generated by scripts/provision.sh -- gitignored, do not commit.
VPN_PUBLIC_IP=$PUBLIC_IP
VPN_ADMIN_USER=$ADMIN_USER
VPN_ADMIN_PASSWORD=$ADMIN_PASSWORD
VPN_IMAGE_EXACT=$IMAGE_EXACT
VPN_AMNEZIAWG_PORT=$AMNEZIAWG_PORT
VPN_XRAY_PORT=$XRAY_PORT
ENVFILE
# umask only governs mode at creation; if .env already existed with weaker
# permissions (leftover from another process, restored from backup, etc.)
# the cat above would rewrite its contents but not tighten its mode. Force
# the guarantee explicitly so it holds regardless of prior file state.
chmod 600 "$REPO_ROOT/.env"

cat <<BANNER

────────────────────────────────────────────────────────────
  Host ready. Enter these into the AmneziaVPN desktop client:

    IP address :  $PUBLIC_IP
    Login      :  $ADMIN_USER
    Password   :  $ADMIN_PASSWORD

  Install AmneziaWG first (it needs no domain or certificate,
  so a failure means the pipeline is wrong, not the protocol).
  Use UDP port $AMNEZIAWG_PORT -- it is already open in the NSG.
  Add XRay REALITY afterwards on TCP $XRAY_PORT.

  Saved to .env (gitignored).
────────────────────────────────────────────────────────────

BANNER
